name: Site scanner

on:
  workflow_dispatch:


jobs:
  DAST-scan:
    name: DAST site scanner
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cluster_ip: ["${{ secrets.CLUSTER_IP }}"]
        port: [31546,31547]

    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: http://${{ matrix.cluster_ip }}:${{ matrix.port}}
          artifact_name: zap_scan_${{ matrix.cluster_ip }}_${{ matrix.port }}
